@bc:shopsystem-messaging @origin:adr-014 @service:postgres
Feature: Presence heartbeat collapsed into shop-msg watch (PDR-010 ADR-014)

  @scenario_hash:c4b41c39d58ee2ef
  Scenario: shop-msg watch --bc <name> UPSERTs a row in bc_presence on the default 30-second cadence carrying the BC name, current timestamp, and a per-process session UUID
  Given a messaging postgres database with a bc_presence table at schema (bc_name TEXT PRIMARY KEY, last_seen_at TIMESTAMPTZ NOT NULL, watch_session_id UUID NOT NULL)
  And NO existing bc_presence row for bc_name "shopsystem-messaging"
  When the BC operator runs "shop-msg watch --bc shopsystem-messaging" and the process is allowed to run for 65 seconds
  Then within the first 30 seconds an INSERT-via-UPSERT against bc_presence inserts a row at (bc_name='shopsystem-messaging', last_seen_at=<approx now-at-insert>, watch_session_id=<UUID generated by this watch process>)
  And on each subsequent 30-second tick the UPSERT updates the same row, advancing last_seen_at to the new now() and leaving watch_session_id unchanged across ticks from the same process
  And by the 65th second the bc_presence row's last_seen_at has been updated at least twice (initial tick + one subsequent tick)
  And the UPSERT is keyed on bc_name (PRIMARY KEY), so the row count for bc_name='shopsystem-messaging' remains exactly one regardless of how many ticks have fired
  And the load-bearing property pinned here is that liveness is emitted by the SAME process that holds the LISTEN connection: a wedged watch loop (LISTEN intact but tick loop stalled) is detectable by the lack of recent last_seen_at, which is what the lead's stale/offline classification surfaces

  @scenario_hash:3efb5c9d29f645d9
  Scenario: shop-msg bc-status reads bc_presence and classifies each BC by age of last_seen_at — online under 90 seconds, stale between 90 seconds and 5 minutes, offline beyond 5 minutes
  Given a messaging postgres database with a bc_presence table containing three rows: (bc_name='bc-fresh', last_seen_at=<now minus 15 seconds>, watch_session_id=<uuid1>); (bc_name='bc-laggy', last_seen_at=<now minus 3 minutes>, watch_session_id=<uuid2>); (bc_name='bc-gone', last_seen_at=<now minus 10 minutes>, watch_session_id=<uuid3>)
  When the lead operator runs "shop-msg bc-status"
  Then the command exits zero
  And the output contains a line for "bc-fresh" classified as "online" with a seconds-since-last-seen value of approximately 15
  And the output contains a line for "bc-laggy" classified as "stale" with a seconds-since-last-seen value of approximately 180
  And the output contains a line for "bc-gone" classified as "offline" with a seconds-since-last-seen value of approximately 600
  And the threshold boundaries are exact per ADR-014 decision 3: <90s is online (90 itself is NOT online); 90s-5min is stale (300 itself is NOT stale; it is offline); >5min is offline
  And the load-bearing property pinned here is that the lead's session-start drain block can call "shop-msg bc-status" to surface offline BCs BEFORE accepting user work, closing failure mode B from PDR-010

  @scenario_hash:3ff862feef699480
  Scenario: shop-msg watch reconnect after a LISTEN drop resumes ticking on the same cadence and the next tick UPSERTs last_seen_at = now(), with no backfill of missed ticks (gap is informational)
  Given a messaging postgres database with a bc_presence row at (bc_name='shopsystem-messaging', last_seen_at=<now minus 45 seconds>, watch_session_id=<uuid1>)
  And a "shop-msg watch --bc shopsystem-messaging" process whose postgres LISTEN connection has dropped (e.g., postgres restarted, network blip, transient unavailability) and is reconnecting per the lead-tsj reconnect mechanism
  When the watch process completes its reconnect (LISTEN re-established) and the next 30-second tick fires
  Then the bc_presence row for bc_name='shopsystem-messaging' has its last_seen_at advanced to the new now() (the moment of the post-reconnect tick)
  And watch_session_id is unchanged from <uuid1> (this is the SAME watch process that reconnected, not a new process)
  And NO backfilled rows or backfilled timestamp updates are written for the missed ticks during the LISTEN drop interval (the gap between the prior last_seen_at and the post-reconnect last_seen_at is informational only, recoverable by inspection of the timestamp delta)
  And during the drop interval, the lead's "shop-msg bc-status" classification for shopsystem-messaging may transition from online to stale (and back to online once the tick fires); this transient transition is the expected behavior and is NOT a flap that downstream tooling must specially handle
  And the load-bearing property pinned here is that reconnect-resumes-ticking, no backfill, is the simplest contract that preserves the classification's load-bearing property: <90s online is always derivable from the most recent tick, regardless of gap history

  @scenario_hash:f6488ec56aefa35e
  Scenario: when two shop-msg watch processes are running for the same BC, both UPSERT the same bc_presence row keyed on bc_name; watch_session_id records the most recent ticker but is informational; last_seen_at always wins for classification
  Given a messaging postgres database with NO existing bc_presence row for bc_name "shopsystem-messaging"
  And two concurrent "shop-msg watch --bc shopsystem-messaging" processes started independently (e.g., a launcher transition where an old watch has not yet exited and a new one has started), with session UUIDs <uuid-old> and <uuid-new> respectively
  When both processes complete their first tick within the same 30-second window, with <uuid-old>'s tick landing first at timestamp T1 and <uuid-new>'s tick landing second at timestamp T2 (T2 > T1)
  Then the bc_presence row count for bc_name='shopsystem-messaging' is exactly one (the UPSERT's PRIMARY KEY on bc_name collapses both inserts into one row)
  And the row's last_seen_at is T2 (the more recent tick wins)
  And the row's watch_session_id is <uuid-new> (informational record of which session most recently ticked)
  And the lead's "shop-msg bc-status" classifies shopsystem-messaging as "online" based on T2's age, regardless of which watch session ticked it
  And the load-bearing property pinned here is per ADR-014 decision 6: the lead cares only whether ANYONE is watching, not how many; multi-watcher races resolve to "the most recent tick wins" without any flapping or classification ambiguity

  @scenario_hash:1d6a55d8636ccb1d
  Scenario: shop-msg bc-status --bc <name> returns just that BC's classification and seconds-since-last-seen, with a clear handling for the case where no bc_presence row exists for that BC
  Given a messaging postgres database with bc_presence rows for "bc-one" (last_seen_at=<now minus 20 seconds>) and "bc-two" (last_seen_at=<now minus 4 minutes>)
  And NO bc_presence row exists for "bc-never-watched"
  When the lead operator runs "shop-msg bc-status --bc bc-two"
  Then the command exits zero and emits exactly one row: "bc-two" classified as "stale" with seconds-since-last-seen approximately 240
  And the output does NOT contain a row for "bc-one" or any other BC
  When the lead operator runs "shop-msg bc-status --bc bc-never-watched"
  Then the command exits zero and emits a row for "bc-never-watched" classified as "offline" with no last_seen_at timestamp (the absence of a bc_presence row is treated as "never observed alive", classified as offline per the fail-safe rollout-window posture from ADR-014 consequences)
  And the load-bearing property pinned here is that the single-BC query form supports the lead's pre-dispatch check ("is shopsystem-X online before I send to it?") without forcing the lead to grep through a full topology listing
