"""Deterministic generator (``decisions build``, Step 2).

Single-source docs -> L0 cards, L1 extracts, ``llms.txt``, ``index.json``,
``DECISIONS.md`` and a ``manifest.lock``, all under ``decision-refs/``. Every
artifact byte is a pure function of the parsed corpus: no timestamps, hostnames,
or absolute paths leak in (D3 §5.4 ambient-state ban). The build is idempotent
(``build && build`` writes zero bytes) and ``--check`` is the drift gate.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile

from . import parser
from .corpus import build_graph, extract_decision, load_corpus
from .schema import ACTIVE_STATUS, lint_document

GENERATOR_VERSION = "1.0.0"
SCHEMA_VERSION = "1.0.0"

REFS_DIR = "decision-refs"
PROVENANCE = "<!-- GENERATED by decisions build — do not edit. -->\n"
KIND_RANK = {"adr": 0, "pdr": 1, "brief": 2}
KIND_LABEL = {"adr": "adr", "pdr": "pdr", "brief": "brief"}


def _sort_key(doc):
    return (KIND_RANK.get(doc.kind, 9), doc.id)


def _yaml_scalar(v) -> str:
    return parser._scalar(v)


def _l0_card(doc) -> str:
    fm = doc.fm
    lines = [PROVENANCE, "```yaml"]
    lines.append(f"id: {_yaml_scalar(fm.get('id'))}")
    lines.append(f"kind: {_yaml_scalar(fm.get('kind'))}")
    lines.append(f"title: {_yaml_scalar(fm.get('title'))}")
    lines.append(f"status: {_yaml_scalar(fm.get('status'))}")
    lines.append(f"description: {_yaml_scalar(fm.get('description'))}")
    tags = fm.get("tags") or []
    lines.append("tags: [" + ", ".join(_yaml_scalar(t) for t in tags) + "]")
    lines.append(f"path: {_yaml_scalar(doc.relpath)}")
    lines.append("```")
    return "\n".join(lines) + "\n"


def _l1_extract(doc, graph) -> str:
    fm = doc.fm
    out = [PROVENANCE, "```yaml"]
    out.append(f"id: {_yaml_scalar(fm.get('id'))}")
    out.append(f"status: {_yaml_scalar(fm.get('status'))}")
    out.append(f"date: {_yaml_scalar(fm.get('date'))}")
    eo = graph.edges_out(doc.id)
    out.append("edges_out:")
    for rel in sorted(eo):
        out.append(f"  {rel}: [" + ", ".join(_yaml_scalar(x) for x in eo[rel]) + "]")
    ei = graph.edges_in(doc.id)
    out.append("edges_in:")
    for rel in sorted(ei):
        out.append(f"  {rel}: [" + ", ".join(_yaml_scalar(x) for x in ei[rel]) + "]")
    invs = fm.get("invariants") or []
    out.append("invariants:")
    for inv in invs:
        out.append(f"  - id: {_yaml_scalar(inv.get('id'))}")
        out.append(f"    statement: {_yaml_scalar(inv.get('statement'))}")
        out.append(f"    hash: {_yaml_scalar(inv.get('hash'))}")
        out.append(f"    status: {_yaml_scalar(inv.get('status', 'unverified'))}")
    out.append("```")
    block = "\n".join(out) + "\n"
    dec = extract_decision(doc.body)
    if dec:
        block += "\n" + dec[0] + "\n\n" + dec[1] + "\n"
    return block


def _card_object(doc, graph) -> dict:
    fm = doc.fm
    return {
        "id": fm.get("id"),
        "kind": fm.get("kind"),
        "title": fm.get("title"),
        "status": fm.get("status"),
        "description": fm.get("description"),
        "tags": list(fm.get("tags") or []),
        "path": doc.relpath,
        "edges_out": graph.edges_out(doc.id),
        "edges_in": graph.edges_in(doc.id),
    }


def _llms_txt(docs, graph) -> str:
    out = ["# shopsystem-product decision index", ""]
    out.append("> Progressive-disclosure index of every ADR / PDR / brief. "
               "L0 = this line; L1 = extract; L2 = the source file.")
    out.append("")
    active = [d for d in docs if d.status in ACTIVE_STATUS]
    retired = [d for d in docs if d.status not in ACTIVE_STATUS]
    for kind in ("adr", "pdr", "brief"):
        group = sorted((d for d in active if d.kind == kind), key=_sort_key)
        if not group:
            continue
        out.append(f"## {kind}")
        out.append("")
        for d in group:
            fm = d.fm
            out.append(
                f"- [{fm.get('id')}](../{d.relpath}) — {fm.get('description')} "
                f"({fm.get('status')}) · [L0](l0/{fm.get('id')}.md) [L1](l1/{fm.get('id')}.md)"
            )
        out.append("")
    if retired:
        out.append("## Superseded / retired")
        out.append("")
        for d in sorted(retired, key=_sort_key):
            fm = d.fm
            out.append(
                f"- [{fm.get('id')}](../{d.relpath}) — {fm.get('description')} "
                f"({fm.get('status')})"
            )
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def _index_json(docs, graph) -> str:
    arr = [_card_object(d, graph) for d in sorted(docs, key=_sort_key)]
    return json.dumps(arr, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def _decisions_md(docs, graph) -> str:
    out = [PROVENANCE.rstrip("\n"), "", "# Decisions (active partition)", ""]
    active = sorted((d for d in docs if d.status in ACTIVE_STATUS), key=_sort_key)
    for d in active:
        fm = d.fm
        out.append(f"## {fm.get('id')} — {fm.get('title')}")
        out.append("")
        out.append(f"Status: {fm.get('status')} · {fm.get('date')}")
        sup = graph.edges_out(d.id).get("supersedes")
        supby = graph.edges_out(d.id).get("superseded-by")
        if sup:
            out.append(f"Supersedes: {', '.join(sup)}")
        if supby:
            out.append(f"Superseded-by: {', '.join(supby)}")
        out.append("")
        dec = extract_decision(d.body)
        if dec:
            out.append(dec[1])
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def render_artifacts(docs, graph) -> dict[str, str]:
    """Return ``{repo-relative-path: content}`` for every generated artifact."""
    arts: dict[str, str] = {}
    for d in sorted(docs, key=_sort_key):
        arts[f"{REFS_DIR}/l0/{d.id}.md"] = _l0_card(d)
        arts[f"{REFS_DIR}/l1/{d.id}.md"] = _l1_extract(d, graph)
    arts[f"{REFS_DIR}/llms.txt"] = _llms_txt(docs, graph)
    arts[f"{REFS_DIR}/index.json"] = _index_json(docs, graph)
    arts[f"{REFS_DIR}/DECISIONS.md"] = _decisions_md(docs, graph)
    return arts


def _sha(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _manifest(arts: dict[str, str]) -> str:
    obj = {
        "generator_version": GENERATOR_VERSION,
        "schema_version": SCHEMA_VERSION,
        "artifacts": {p: _sha(arts[p]) for p in sorted(arts)},
    }
    return json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def _atomic_write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    d = os.path.dirname(path)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".tmp-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)


class BuildError(Exception):
    """Raised when the corpus has blocking lint errors (build writes nothing)."""

    def __init__(self, findings):
        self.findings = findings
        super().__init__("lint failures block the build")


def build(dirs: list[str], base: str = ".", check: bool = False) -> dict:
    """Run the pipeline. Returns a result dict.

    On lint failure raises :class:`BuildError`. In ``check`` mode, returns
    ``{"drift": [paths]}``; drift non-empty means the on-disk artifacts differ
    from a fresh build. In write mode, returns ``{"written": [...], "pruned": [...]}``.
    """
    res = load_corpus(dirs, base)
    findings = []
    ids: dict[str, str] = {}
    for d in res.docs:
        if d.id and d.id not in ids:
            ids[d.id] = d.path
    for path, msg in res.parse_errors:
        from .model import Finding, SEV_LINT
        findings.append(Finding("COH-LN-001", SEV_LINT, path,
                                f"unparseable frontmatter: {msg}",
                                "add a valid '---' frontmatter fence"))
    for d in res.docs:
        findings.extend(lint_document(d, ids))
    if findings:
        raise BuildError(findings)

    graph = build_graph(res.docs)
    arts = render_artifacts(res.docs, graph)
    arts[f"{REFS_DIR}/manifest.lock"] = _manifest(
        {k: v for k, v in arts.items()})

    refs_root = os.path.join(base, REFS_DIR)

    if check:
        drift = []
        for rel, content in arts.items():
            disk = os.path.join(base, rel)
            if not os.path.exists(disk):
                drift.append(rel + " (missing)")
                continue
            with open(disk, "r", encoding="utf-8") as fh:
                if fh.read() != content:
                    drift.append(rel + " (differs)")
        # orphans on disk not in manifest
        for orphan in _existing_artifacts(refs_root):
            if orphan not in arts:
                drift.append(orphan + " (orphan)")
        return {"drift": sorted(drift)}

    written, pruned = [], []
    for rel, content in arts.items():
        disk = os.path.join(base, rel)
        if os.path.exists(disk):
            with open(disk, "r", encoding="utf-8") as fh:
                if fh.read() == content:
                    continue
        _atomic_write(disk, content)
        written.append(rel)
    for orphan in _existing_artifacts(refs_root):
        if orphan not in arts:
            os.remove(os.path.join(base, orphan))
            pruned.append(orphan)
    return {"written": sorted(written), "pruned": sorted(pruned)}


def _existing_artifacts(refs_root: str) -> list[str]:
    """Repo-relative artifact paths currently on disk (prune candidates).

    ``coherence-lock.yaml`` is exempt (owned by ``decisions baseline``)."""
    out = []
    base = os.path.dirname(refs_root)
    for sub in ("l0", "l1"):
        d = os.path.join(refs_root, sub)
        if os.path.isdir(d):
            for name in os.listdir(d):
                out.append(os.path.relpath(os.path.join(d, name), base))
    for root_art in ("llms.txt", "index.json", "DECISIONS.md", "manifest.lock"):
        p = os.path.join(refs_root, root_art)
        if os.path.exists(p):
            out.append(os.path.relpath(p, base))
    return out
